-- Remove Basketball and Athletics from sports table
DELETE FROM sports WHERE slug IN ('basketball', 'athletics');

-- Add the three missing new sports
INSERT INTO sports (name, slug, description, rules) VALUES
('100m Race', '100m-race', '100m Race is a sprint event that tests pure speed, explosive power, and acceleration. Athletes race in a straight line for 100 meters, making it one of the shortest and most intense track events. Success requires perfect starting technique, maximum acceleration, and sustained top speed. The race is over in seconds but demands years of training. It is one of the most prestigious events in athletics. The 100m sprint crowns the fastest human on Earth.', 'Athletes compete in a straight 100-meter sprint. Standard IAAF track and field rules apply. Races use starting blocks and electronic timing. False starts result in disqualification. Fastest time wins.'),

('Relay', 'relay', 'Relay is a team-based running event where athletes pass a baton to teammates in sequence. The most common format is the 4x100m relay, requiring speed, precision, and flawless baton exchanges. Teams must coordinate timing and positioning to minimize time loss during handoffs. The sport combines individual speed with team synchronization. Dropped batons or missed exchanges can cost the race. Relay events are highlights of major track competitions.', 'Teams of 4 runners each complete a leg of the race (typically 100m each). A baton must be passed within a designated exchange zone. Dropping the baton or passing outside the zone results in disqualification. Standard relay rules apply. Fastest team wins.'),

('Shot Put', 'shot-put', 'Shot Put is a field event where athletes throw a heavy spherical ball (shot) as far as possible. It requires explosive strength, technique, rotational power, and balance. Athletes use either the glide or spin technique to generate maximum throwing distance. The event tests upper body strength, core stability, and coordination. Throws must be made from within a designated circle. Shot Put is a classic strength event in track and field competitions.', 'Athletes throw a metal shot (7.26kg for men, 4kg for women) from inside a throwing circle. The throw must land within a marked sector. Athletes cannot step outside the circle during or after the throw. Longest valid throw wins. Standard IAAF field event rules apply.');